In [6]:
import pandas as pd
import numpy as np

# Read the CSV file
df = pd.read_csv('/home/azureuser/cloudfiles/code/Users/Akshayanivashini.ChandrasekarVijayalakshmi/Skinly_Thailand/Akshay_projects2/updated_thai_chunkid.csv')

In [7]:
# Define a function to remove outliers using the z-score method
def remove_outliers_zscore(df, features, threshold=3):
    z_scores = np.abs((df[features] - df[features].mean()) / df[features].std())
    df = df[(z_scores < threshold).all(axis=1)]
    return df

In [8]:

# Define a list of features to check for outliers
features = ['moisture_cheek', 'moisture_forearm', 'moisture_forehead', 'shininess_cheek', 'shininess_forehead', 'evenness_cheek', 'evenness_forearm', 'evenness_red_cheek', 'evenness_red_forearm', 'evenness_red_forehead', 'ita_cheek', 'ita_forearm', 'ita_forehead', 'melanin_cheek', 'melanin_forearm', 'melanin_forehead', 'vessels_den_cheek', 'vessels_den_forearm', 'vessels_den_forehead', 'skin_texture_cheek', 'skin_texture_forearm', 'skin_texture_forehead', 'fine_lines_cheek', 'fine_lines_forearm', 'fine_lines_forehead', 'deep_lines_forehead', 'cheek_age_dif', 'forearm_age_dif', 'forehead_age_dif', 'G_porph_L_MEAN_cheek', 'G_porph_L_MEAN_forehead', 'G_porph_NUMBER_cheek', 'G_porph_NUMBER_forehead', 'R_porph_L_MEAN_cheek', 'R_porph_L_MEAN_forehead', 'R_porph_NUMBER_cheek', 'R_porph_NUMBER_forehead', 'Y_porph_L_MEAN_cheek', 'Y_porph_L_MEAN_forehead', 'Y_porph_NUMBER_cheek', 'Y_porph_NUMBER_forehead', 'redness_cheek', 'redness_forearm', 'redness_forehead']

In [9]:
# Remove outliers using the z-score method
df = remove_outliers_zscore(df, features)

In [10]:

# Save the updated data to a new CSV file
df.to_csv('outliers_removed_thai.csv', index=False)

In [11]:
df.head()

,user_id,date,chunkiduser,moisture_cheek,moisture_forearm,moisture_forehead,shininess_cheek,shininess_forehead,evenness_cheek,evenness_forearm,...,R_porph_L_MEAN_forehead,R_porph_NUMBER_cheek,R_porph_NUMBER_forehead,Y_porph_L_MEAN_cheek,Y_porph_L_MEAN_forehead,Y_porph_NUMBER_cheek,Y_porph_NUMBER_forehead,redness_cheek,redness_forearm,redness_forehead
94,3154,2023-04-23,chunk1,100.0,56.0,76.0,3.0,33.0,36.0,24.0,...,15.0,1.0,51.0,0.0,16.0,0.0,3.0,25.0,4.0,45.0
98,3154,2023-04-27,chunk1,21.0,46.0,48.0,3.0,37.0,63.0,44.0,...,14.0,1.0,45.0,21.0,12.0,1.0,3.0,38.0,7.0,60.0
108,3154,2023-05-07,chunk1,40.0,39.0,39.0,10.0,28.0,61.0,50.0,...,14.0,0.0,15.0,0.0,0.0,0.0,0.0,32.0,1.0,65.0
110,3154,2023-05-09,chunk1,14.0,39.0,38.0,2.0,27.0,45.0,52.0,...,15.0,0.0,30.0,0.0,16.0,0.0,3.0,22.0,3.0,44.0
225,3181,2022-01-22,chunk1,91.0,83.0,88.0,69.0,82.0,49.0,47.0,...,19.0,51.0,138.0,22.0,16.0,5.0,12.0,48.0,2.0,58.0

### Normalization using Min-Max

In [20]:
! pip install scikit-learn

Requirement already satisfied: scikit-learn in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (0.22.1)
Requirement already satisfied: numpy>=1.11.0 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from scikit-learn) (1.22.3)
Requirement already satisfied: scipy>=0.17.0 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=0.11 in /anaconda/envs/azureml_py38/lib/python3.8/site-packages (from scikit-learn) (1.2.0)

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [22]:


# Read the CSV file
df = pd.read_csv('/home/azureuser/cloudfiles/code/Users/Akshayanivashini.ChandrasekarVijayalakshmi/Skinly_Thailand/Akshay_projects2/outliers_removed_thai.csv')

In [23]:
# Define a list of features to normalize and scale
features = ['moisture_cheek', 'moisture_forearm', 'moisture_forehead', 'shininess_cheek', 'shininess_forehead', 'evenness_cheek', 'evenness_forearm', 'evenness_red_cheek', 'evenness_red_forearm', 'evenness_red_forehead', 'ita_cheek', 'ita_forearm', 'ita_forehead', 'melanin_cheek', 'melanin_forearm', 'melanin_forehead', 'vessels_den_cheek', 'vessels_den_forearm', 'vessels_den_forehead', 'skin_texture_cheek', 'skin_texture_forearm', 'skin_texture_forehead', 'fine_lines_cheek', 'fine_lines_forearm', 'fine_lines_forehead', 'deep_lines_forehead', 'cheek_age_dif', 'forearm_age_dif', 'forehead_age_dif', 'G_porph_L_MEAN_cheek', 'G_porph_L_MEAN_forehead', 'G_porph_NUMBER_cheek', 'G_porph_NUMBER_forehead', 'R_porph_L_MEAN_cheek', 'R_porph_L_MEAN_forehead', 'R_porph_NUMBER_cheek', 'R_porph_NUMBER_forehead', 'Y_porph_L_MEAN_cheek', 'Y_porph_L_MEAN_forehead', 'Y_porph_NUMBER_cheek', 'Y_porph_NUMBER_forehead', 'redness_cheek', 'redness_forearm', 'redness_forehead']

In [24]:
# Normalize and scale the features to the range 0-100
scaler = MinMaxScaler(feature_range=(0, 100))
df[features] = scaler.fit_transform(df[features])

In [25]:
# Save the updated data to a new CSV file
df.to_csv('normalised_thai.csv', index=False)

In [26]:
df.head()

,user_id,date,chunkiduser,moisture_cheek,moisture_forearm,moisture_forehead,shininess_cheek,shininess_forehead,evenness_cheek,evenness_forearm,...,R_porph_L_MEAN_forehead,R_porph_NUMBER_cheek,R_porph_NUMBER_forehead,Y_porph_L_MEAN_cheek,Y_porph_L_MEAN_forehead,Y_porph_NUMBER_cheek,Y_porph_NUMBER_forehead,redness_cheek,redness_forearm,redness_forehead
0,3154,2023-04-23,chunk1,100.0,54.166667,76.0,3.225806,30.927835,42.241379,22.077922,...,39.473684,1.149425,28.491620,0.000000,44.444444,0.000000,4.918033,34.042553,30.588235,45.217391
1,3154,2023-04-27,chunk1,21.0,43.750000,48.0,3.225806,35.051546,65.517241,48.051948,...,36.842105,1.149425,25.139665,51.219512,33.333333,4.166667,4.918033,47.872340,34.117647,58.260870
2,3154,2023-05-07,chunk1,40.0,36.458333,39.0,10.752688,25.773196,63.793103,55.844156,...,36.842105,0.000000,8.379888,0.000000,0.000000,0.000000,0.000000,41.489362,27.058824,62.608696
3,3154,2023-05-09,chunk1,14.0,36.458333,38.0,2.150538,24.742268,50.000000,58.441558,...,39.473684,0.000000,16.759777,0.000000,44.444444,0.000000,4.918033,30.851064,29.411765,44.347826
4,3181,2022-01-22,chunk1,91.0,82.291667,88.0,74.193548,81.443299,53.448276,51.948052,...,50.000000,58.620690,77.094972,53.658537,44.444444,20.833333,19.672131,58.510638,28.235294,56.521739

In [3]:
import pandas as pd

# Load the dataset
dfout= pd.read_csv('/home/azureuser/cloudfiles/code/Users/Akshayanivashini.ChandrasekarVijayalakshmi/Skinly_Thailand/Akshay_projects2/outliers_removed_thai.csv')

# Calculate the z-scores for each column
z_scores = (dfout[dfout.columns[3:]] - dfout[dfout.columns[3:]].mean()) / dfout[dfout.columns[3:]].std()

# Scale the data between 0 and 100
scaled_data = z_scores * 50 + 50
# Clip the scaled values to a maximum of 100
scaled_data = scaled_data.clip(upper=100)

# Replace the original data with the scaled data
dfout[dfout.columns[3:]] = scaled_data

# Save the standardized and scaled data to a new CSV file
dfout.to_csv('z_score_normalized.csv', index=False)

In [7]:
from sklearn.preprocessing import StandardScaler

In [5]:
# Load the dataset
dfout2= pd.read_csv('/home/azureuser/cloudfiles/code/Users/Akshayanivashini.ChandrasekarVijayalakshmi/Skinly_Thailand/Akshay_projects2/outliers_removed_thai.csv')

In [8]:
# Select the columns to standardize
cols_to_standardize = dfout2.columns[3:]

# Standardize the data
scaler = StandardScaler()
dfout2[cols_to_standardize] = scaler.fit_transform(dfout2[cols_to_standardize])

# Scale the data between 0 and 100
dfout2[cols_to_standardize] = dfout2[cols_to_standardize] * 50 + 50

# Save the standardized and scaled data to a new CSV file
dfout2.to_csv('standardized_scaled.csv', index=False)

In [4]:
dfout

,user_id,date,chunkiduser,moisture_cheek,moisture_forearm,moisture_forehead,shininess_cheek,shininess_forehead,evenness_cheek,evenness_forearm,...,R_porph_L_MEAN_forehead,R_porph_NUMBER_cheek,R_porph_NUMBER_forehead,Y_porph_L_MEAN_cheek,Y_porph_L_MEAN_forehead,Y_porph_NUMBER_cheek,Y_porph_NUMBER_forehead,redness_cheek,redness_forearm,redness_forehead
0,3154,2023-04-23,chunk1,100.000000,49.201075,92.843936,-87.979348,-18.024649,17.465417,-13.356679,...,75.414211,29.648781,100.000000,19.13027,99.816899,29.368639,52.413561,11.695559,9.593151,58.184218
1,3154,2023-04-27,chunk1,-41.425534,20.355659,20.814102,-87.979348,-6.670398,90.917604,61.114678,...,69.981513,29.648781,100.000000,100.00000,77.905705,46.204204,52.413561,56.552407,20.335927,96.799142
2,3154,2023-05-07,chunk1,8.354613,0.163867,-2.338345,-65.258783,-32.217464,85.476701,83.456084,...,69.981513,25.279462,57.915619,19.13027,12.172125,29.368639,30.600621,35.849246,-1.149626,100.000000
3,3154,2023-05-09,chunk1,-59.765588,0.163867,-4.910839,-91.225143,-35.056027,41.949479,90.903220,...,75.414211,25.279462,86.273993,19.13027,99.816899,29.368639,52.413561,1.343978,6.012225,55.609890
4,3181,2022-01-22,chunk1,100.000000,100.000000,100.000000,100.000000,100.000000,52.831285,72.285381,...,97.145003,100.000000,100.000000,100.00000,99.816899,100.000000,100.000000,91.057674,2.431299,91.650485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8635,21590,2024-03-14,chunk1,-12.605449,29.009284,7.951632,22.377683,18.876669,52.831285,-13.356679,...,80.846909,60.234019,35.228920,100.00000,12.172125,79.875333,30.600621,15.146085,45.402407,32.440936
8636,21590,2024-03-15,chunk1,8.354613,20.355659,15.669114,100.000000,16.038106,28.347222,-13.356679,...,97.145003,73.341977,93.836226,100.00000,100.000000,79.875333,59.684542,39.299773,34.659630,58.184218
8637,21590,2024-03-16,chunk1,16.214636,40.547450,59.401513,100.000000,100.000000,-31.502708,-9.633111,...,97.145003,60.234019,61.696735,100.00000,100.000000,63.039768,88.768463,32.398719,34.659630,50.461234
8638,21590,2024-03-17,chunk1,10.974621,34.778367,31.104078,51.589838,78.486490,6.583611,-13.356679,...,97.145003,51.495379,73.040085,19.13027,100.000000,29.368639,81.497482,1.343978,38.240555,29.866608
8639,21590,2024-03-18,chunk1,-4.745426,37.662909,10.524126,6.148708,92.679305,-4.298194,8.984728,...,91.712305,60.234019,61.696735,100.00000,100.000000,79.875333,59.684542,-5.557075,41.821481,22.143624

In [9]:
dfout2.head()

,user_id,date,chunkiduser,moisture_cheek,moisture_forearm,moisture_forehead,shininess_cheek,shininess_forehead,evenness_cheek,evenness_forearm,...,R_porph_L_MEAN_forehead,R_porph_NUMBER_cheek,R_porph_NUMBER_forehead,Y_porph_L_MEAN_cheek,Y_porph_L_MEAN_forehead,Y_porph_NUMBER_cheek,Y_porph_NUMBER_forehead,redness_cheek,redness_forearm,redness_forehead
0,3154,2023-04-23,chunk1,165.561765,49.201029,92.846416,-87.987334,-18.028586,17.463534,-13.360346,...,75.415682,29.647604,125.980113,19.128484,99.819782,29.367445,52.413701,11.693342,9.590812,58.184692
1,3154,2023-04-27,chunk1,-41.430825,20.353943,20.812413,-87.987334,-6.673677,90.919972,61.115321,...,69.982670,29.647604,114.636107,116.583559,77.907320,46.203984,52.413701,56.552786,20.334211,96.801850
2,3154,2023-05-07,chunk1,8.352203,0.160983,-2.341374,-65.265454,-32.222222,85.478754,83.458021,...,69.982670,25.278031,57.916077,19.128484,12.169936,29.367445,30.599498,35.848427,-1.152586,109.674236
3,3154,2023-05-09,chunk1,-59.771941,0.160983,-4.914017,-91.233317,-35.060950,41.949013,90.905587,...,75.415682,25.278031,86.276092,19.128484,99.819782,29.367445,52.413701,1.341162,6.009679,55.610215
4,3181,2022-01-22,chunk1,141.980331,127.088162,123.718131,126.247537,121.069047,52.831448,72.286671,...,97.147732,248.126227,290.468201,121.224277,99.819782,113.550139,117.856310,91.060050,2.428546,91.652896